print("What is your name?")
name = input()
print("Hello, " + name)
############################################################
print("First Number:")
first_number = int(input())
print("Second Number:")
second_number = int(input())
sum = first_number + second_number
print("Sum: " + str(sum))
################################################################
print("Today's date?")
tod_data = input()
print("Breakfast calories?")
break_cal=int(input())
print('Lunch calories?')
lanch_cal=int(input())
print('Dinner calories?')
dinner_cal=int(input())
print('Snack calories?')
snack_cal=int(input())
res=break_cal+lanch_cal+dinner_cal+snack_cal
print('Calorie content for '+tod_data +': ' + str( res))
#print(("Calorie content for Thursday : " + str(result_today))
################################################################
print(type(7))
print(type(True))
print(type(False))
print(type('True'))
print(bool('True'))
print(bool('False'))
print(bool(''))
print(bool(0))
print(bool(' '))
print(bool('Hello world!'))
print(1 + 1 == 3)
print(1 + 1 == 2)
print(3 == 4)
print(3 != 4)
print(3 > 4)
print(3 < 4)
print(3 >= 4)
print(3 <= 4)
i=5
print(type(i))
